const actionTypes = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',

  PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
  PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
  PRODUCT_DETAIL_FAIL: 'PRODUCT_DETAIL_FAIL',
};

export default actionTypes;
